[package]
name = "bettertimer"
description = "`sleep` with progress and notifications, written in rust"
version = "1.0.6"
license = "GPL-3.0-or-later"
edition = "2024"
repository = "https://github.com/clorine-software/bettertimer"
homepage = "https://github.com/clorine-software/bettertimer"
authors = ["clorine-software", "nd1", "slawacats"]

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
humantime = "2.4.0"
indicatif = "0.18.6"
notify-rust = "4.18.0"
tokio = { version = "1.53.1", features = ["full"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
